# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b449bc5070a95a13cf55cf0f59b371fd34af29152cd4c03731a2bfaed43a9c939b19e0c7acae00078474a139109379922c3c6a9891cc4e7d7c2dbb0db01a3b7

test:
  secret_key_base: 5ffbab7e24ca5f525a4a655d5741d20b3f1d01520fa65cf7a39305b112d3a1ee110cfe8af5f0da0fbb92179270b196b82fcc3d3ba64e9f45f933237043838182

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
